# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install python and requirements
        run: |
          apt install python python-pip -y
          python -m pip install requests

      - name: show raw config url
        run: ls -l profiles/surge | grep -v my.list | awk 'NR >1  {print "https://raw.githubusercontent.com/gitbjjtw/myfile/main/profiles/surge/"$NF}' > tmp.txt

      - name: send msg
        run: python profiles/main.py
